/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'menlo', 'monospace'],
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          hover: 'hsl(var(--primary-hover))',
          deep: 'hsl(var(--primary-deep))',
          subtle: 'hsl(var(--primary-subtle))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          hover: 'hsl(var(--accent-hover))',
          subtle: 'hsl(var(--accent-subtle))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          subtle: 'hsl(var(--success-subtle))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          subtle: 'hsl(var(--warning-subtle))',
        },
        error: {
          DEFAULT: 'hsl(var(--destructive))',
          subtle: 'hsl(var(--error-subtle))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        bg: {
          DEFAULT: 'hsl(var(--bg))',
          elevated: 'hsl(var(--bg-elevated))',
        },
        surface: {
          950: 'hsl(var(--surface-950))',
          900: 'hsl(var(--surface-900))',
          850: 'hsl(var(--surface-850))',
          800: 'hsl(var(--surface-800))',
          750: 'hsl(var(--surface-750))',
          700: 'hsl(var(--surface-700))',
          600: 'hsl(var(--surface-600))',
        },
        ink: {
          primary: 'hsl(var(--ink-primary))',
          secondary: 'hsl(var(--ink-secondary))',
          muted: 'hsl(var(--ink-muted))',
        },
      },
      borderRadius: {
        card: 'var(--radius-card)',
        compose: '16px',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        glow: '0 0 0 1px hsl(var(--ring) / 0.35), 0 0 24px -6px hsl(var(--ring) / 0.35)',
        'glow-strong': '0 0 0 1px hsl(var(--ring) / 0.5), 0 0 36px -6px hsl(var(--ring) / 0.5)',
        'card-lift':
          '0 4px 12px -2px rgba(0, 0, 0, 0.45), 0 1px 3px rgba(0, 0, 0, 0.4)',
        'soft-panel': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.03)',
        subtle: '0 1px 2px rgba(0, 0, 0, 0.25)',
        panel: '0 8px 24px rgba(0, 0, 0, 0.22)',
        floating: '0 16px 48px rgba(0, 0, 0, 0.35)',
        'focus-ring': '0 0 0 1px rgba(139,92,246,0.35), 0 8px 30px rgba(109,40,217,0.18)',
      },
      backgroundImage: {
        'primary-glow':
          'radial-gradient(120% 120% at 50% 0%, hsl(var(--primary-subtle)) 0%, transparent 55%)',
        'app-aurora':
          'radial-gradient(90% 60% at 50% -10%, hsl(var(--primary-subtle)) 0%, transparent 60%), radial-gradient(60% 40% at 90% 0%, hsl(var(--accent)/0.06) 0%, transparent 55%)',
        'mesh-fade':
          'linear-gradient(180deg, hsl(var(--surface-900)/0.6) 0%, transparent 100%)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-600px 0' },
          '100%': { backgroundPosition: '600px 0' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.55' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(6px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(16px) scale(0.99)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'loader-ring': {
          '0%': { transform: 'scale(0.55)', opacity: '0.9' },
          '100%': { transform: 'scale(1.55)', opacity: '0' },
        },
        'loader-glow': {
          '0%, 100%': { opacity: '0.55', transform: 'scale(0.92)' },
          '50%': { opacity: '1', transform: 'scale(1.08)' },
        },
        'loader-breathe': {
          '0%, 100%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '50%': { transform: 'scale(1.06)', filter: 'brightness(1.18)' },
        },
        'loader-sweep': {
          '0%': { transform: 'translateX(-120%)' },
          '60%': { transform: 'translateX(230%)' },
          '100%': { transform: 'translateX(250%)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 1.6s linear infinite',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        'fade-in': 'fade-in 0.3s ease-out both',
        'fade-up': 'fade-up 0.45s cubic-bezier(0.22, 1, 0.36, 1) both',
        'loader-ring': 'loader-ring 2.2s cubic-bezier(0.22, 1, 0.36, 1) infinite',
        'loader-glow': 'loader-glow 2.4s ease-in-out infinite',
        'loader-breathe': 'loader-breathe 2.4s ease-in-out infinite',
        'loader-sweep': 'loader-sweep 1.8s ease-in-out infinite',
      },
    },
  },
  safelist: [
    'btn-primary',
    'btn-secondary',
    'btn-ghost',
    'input',
    'card',
    'card-interactive',
    'focus-ring',
    'checkerboard',
    'glass',
    'glass-panel',
    'glass-hover',
    'glass-active',
    'glass-border',
    'glass-border-bottom',
    'glass-border-top',
    'glass-border-left',
    'text-gradient',
    'scrollbar-thin',
    'no-scrollbar',
    'bd-subtle',
    'bd-hover',
    'bd-active',
    'hover-bd-hover:hover',
    'surface-elevated',
    'surface-hover',
    'focus-glow',
    'workspace-bg',
    'premium-card',
    'addon-shell',
    'pb-safe',
    'mb-safe',
    'pt-safe',
    'mt-safe',
    'touch-target',
    'agent-status-rail',
    'agent-side-rail',
    'agent-side-rail__header',
    'agent-side-rail__title',
    'agent-side-rail__close',
    'agent-card',
    'agent-card--context',
    'agent-card--todo',
    'agent-card__header',
    'agent-card__icon',
    'agent-card__title',
    'agent-card__count',
    'agent-card__chevron',
    'agent-card__body',
    'context-chip',
    'status-event',
    'status-event--open',
    'status-event--close',
    'todo-row',
    'todo-row--cancelled',
    'todo-row__check',
    'todo-row__check--done',
    'todo-row__check--active',
    'todo-row__text',
    'todo-row__text--done',
    'todo-row__text--cancelled',
  ],
  plugins: [require('tailwindcss-animate')],
};